### ISSUE TITLE
deployment my code from git repository, without the participation of the local machine

### ISSUE THREAD

**Issue by Argentum88** [andres-montanez/Magallanes#102]
Hello!

I want to deploy my code from the git repository, without saving it on my local machine. As I understand it, for this is the git-rebase strategy.

As in this case the deploy my code from a particular branch? How to specify parameter branch?

Thanks!

**Comment by czettnersandor** [comment]
I'm happy that I found this awesome project and I really miss this feature too.

We are using Capistrano at the moment and trying to switch to Magallanes. Capistrano can use SSH Agent to forward the key to the remote machine and deploying from git is the default behaviour (Never used Capistrano another way)

**Comment by andres-montanez** [comment]
Hi, Version 1 of Magallanes has long reached it's end of life cycle, so no further changes will be integrated to it, focus is for the next next mayor version.
Many thanks!
