### ISSUE TITLE
Shell arguments (esp. folder names) are not being escaped

### ISSUE THREAD

**Issue by CodeMonkey90** [andres-montanez/Magallanes#103]
I just noticed that shell arguments don't seem to be escaped anywhere, which means that e.g. deployment will not work if your local project folder contains spaces in its name.

**Comment by bglover** [comment]
If you're using PHP 5.5+ you can set the php.ini parameter of sys_temp_dir to: 

``` ini
sys_temp_dir = "/c/Users/Username/AppData/Local/Temp"
```

That worked for me deploying from Windows 8.1

**Comment by andres-montanez** [comment]
Hi, Version 1 of Magallanes has long reached it's end of life cycle, so no further changes will be integrated to it, focus is for the next next mayor version.
If you have directories with spaces, you can scape them in the configuration
`path: /var/web/document\ root`
Still this is a discouraged practice.
Many thanks!
