### ISSUE TITLE
Sudo management

### ISSUE THREAD

**Issue by guepe** [andres-montanez/Magallanes#111]
in runCommandRemote  integrate the option to use sudo commande instead of using apache or root.
it could be a simple option to set and then add the sudo keyword in the command line.

Could also list all commands needed for a sudo and suggest a visudo config.

Thanks :)

**Comment by drAlberT** [comment]
@eps90 if sudo is smell having to be *root* is ? ..  ;) :+1: for avoiding chown/chmod as possible, giving a set of choices to the user via config parameters: use_sudo (t/f), run_chown (t/f), and so on ..

**Comment by drAlberT** [comment]
I'll be more clear .. there are some "maybe-fisrt-deploy-only" tasks (i.e. setfacl) that can only be run by root. sudo is the less smelling solution IMHO

**Comment by eps90** [comment]
Why do you think that tasks like `setfacl`, `chown` or `chmod` can be run only on first time deploy?

**Comment by drAlberT** [comment]
@eps90 because of the man page of `setfacl`  ;)

    The file owner and processes capable of CAP_FOWNER are granted the right to modify ACLs of a file. 
    This is analogous to the permissions required for accessing the file mode.
    (On current Linux systems, root is the only user with the CAP_FOWNER capability.)

**Comment by andres-montanez** [comment]
Hi all, Version 1 of Magallanes has long reached it's end of life cycle, this feature will be available in the next mayor version.
Many thanks to all!
