### ISSUE TITLE
Clean up releases after post-deploy stage. Only if all works done.

### ISSUE THREAD

**Issue by gudron** [andres-montanez/Magallanes#155]
Question is related with the rollback task PR[#154](https://github.com/andres-montanez/Magallanes/pull/154).

Case:
We have 4 successful release. 
And max count of releases is 4.

```
$ ls -l
lrwxrwxrwx 1 user user    23 Nov 13 12:31 current -> releases/20141113122225
drwxr-xr-x 6 user user  4096 Nov 13 12:31 releases

ls -l releases/
drwxrwx--T 6 user user      4096 Nov 13 12:10 20141113120859
drwxrwx--T 6 user user      4096 Nov 13 12:14 20141113121241
drwxrwx--T 6 user user      4096 Nov 13 12:21 20141113121919
drwxrwx--T 6 user user      4096 Nov 13 12:24 20141113122225
```

Ok. And next release will be failed at post-deploy stage. 
In my case - for example - because fail at [codeception tests](http://codeception.com/).

Once will be rolled back - in the list of releases will be one less. Because the directory is cleared after the "on-deploy" stage, and before the "post-release" stage.

During the rollback will remove a directory with a failed build. And change the symbolic link to the previous release

Directory before the release:

```
$ ls -l
lrwxrwxrwx 1 user user    23 Nov 13 12:31 current -> releases/20141113122225
drwxr-xr-x 6 user user  4096 Nov 13 12:31 releases

ls -l releases/
drwxrwx--T 6 user user      4096 Nov 13 12:10 20141113120859
drwxrwx--T 6 user user      4096 Nov 13 12:14 20141113121241
drwxrwx--T 6 user user      4096 Nov 13 12:21 20141113121919
drwxrwx--T 6 user user      4096 Nov 13 12:24 20141113122225
drwxrwx--T 6 user user      4096 Nov 13 12:24 20141113136891 # new build
```

Directory after release:
_20141113120859 deleted_.

```
$ ls -l
lrwxrwxrwx 1 user user    23 Nov 13 12:31 current -> releases/20141113136891 # linked to new build
drwxr-xr-x 6 user user  4096 Nov 13 12:31 releases

ls -l releases/
drwxrwx--T 6 user user      4096 Nov 13 12:14 20141113121241
drwxrwx--T 6 user user      4096 Nov 13 12:21 20141113121919
drwxrwx--T 6 user user      4096 Nov 13 12:24 20141113122225
drwxrwx--T 6 user user      4096 Nov 13 12:24 20141113136891 # new build
```

Directory after rollback:
_New build deleted_

```
$ ls -l
lrwxrwxrwx 1 user user    23 Nov 13 12:31 current -> releases/20141113122225 # linked to previous build
drwxr-xr-x 6 user user  4096 Nov 13 12:31 releases

ls -l releases/
drwxrwx--T 6 user user      4096 Nov 13 12:14 20141113121241
drwxrwx--T 6 user user      4096 Nov 13 12:21 20141113121919
drwxrwx--T 6 user user      4096 Nov 13 12:24 20141113122225
```

It's not a bad situation. While we will have fallen build, we will have the same number of releases in the release directory. In my case - 3.

But in my opinion there is something wrong in the process of cleaning the release directory. Cleaning now ignores the probability of rollback.

I would like to know what is the opinion of the community about the idea.

**Comment by eps90** [comment]
Hey sorry for such delay.
If the problem still exists, it surely should be fixed because it makes unwanted mess in a target server. I'll take a look on that. Thanks!

**Comment by andres-montanez** [comment]
Hi all, Version 1 of Magallanes has long reached it's end of life cycle, this feature will be available in the next mayor version. The cleanup task will be executed after all releases are done, so it's safe to delete them at that stage, because deploy and release tasks went ok.
Many thanks to all!
