### ISSUE TITLE
Adding Coverage to Magallanes code

### ISSUE THREAD

**Issue by SenseException** [andres-montanez/Magallanes#163]
Since the first tests are in development branch, we should think about adding code coverage to the project.

I saw that some projects are using Coveralls (https://coveralls.io/), but I'm not that familiar with this service. Are there other code coverage services that can be added to github?

**Comment by eps90** [comment]
@SenseException @jhuet Yup, we should add code coverage indicator.
Developers should also run tests with code coverage reporting, e.g. by:

    ./bin/phpunit --coverage-text

or even

    ./bin/phpunit --coverge-html report

PS1: The `bin/phpunit` has been added by in #162 . It still waits for approval...
PS2: @jhuet As you've mentioned in #174 , we need to compose some documentation for contributors. With no rules here's gonne be the armageddon...

**Comment by eps90** [comment]
@SenseException @jhuet I've added a PR with travis and coveralls configuration. Please take a look on it.

**Comment by eps90** [comment]
Issue moved to #201 . Closing.
