### ISSUE TITLE
Work around 'chown' command

### ISSUE THREAD

**Issue by limfinity** [andres-montanez/Magallanes#168]
Hi everybody,

I have a webspace with SSH control. But I am not allowed to use the 'chown' command. Only from a web-backend I am allowed to change ownerships. Is there a way to make mage deployment work without using 'chown'? 
Thanks for your help!

Peter

**Comment by andres-montanez** [comment]
Hi, Version 1 of Magallanes has long reached it's end of life cycle, so no further changes will be integrated to it, focus is for the next next mayor version.
Many thanks!
