### ISSUE TITLE
Rsync should remove deleted files

### ISSUE THREAD

**Issue by ramunasd** [andres-montanez/Magallanes#169]
Even file is removed from repo, it stays in servers untouched. Rsync doesn't takes in effect file removals, only creation and update.

**Comment by MasterB** [comment]
+1  (maybe implement rsync --delete-{before/after} options, configurable)

**Comment by eps90** [comment]
Thanks and @ramunasd  @MasterB for suggestion, we'll surely take a look on that! ;)

**Comment by MasterB** [comment]
I found something that works for me and it is already implemented:

{environment}.yml
deployment:
    strategy_flags: {rsync:'--delete-before'}

is this feature only not documented? 
or is it not stable?

**Comment by eps90** [comment]
Well I took a quick look into the code and it seems it's just a string appended to `rsync` command if given. So - yes, you can use it but on your own risk.
Documentation, I hope, is on the way, but first we write unit tests for existing code. Well for some devz tests are documentation of code themselves if class is fully covered but I'm sure that more friendly documentation would be a plus here. Feel free to contribute and discuss about Magallanes' future :) Take a look at #174 :)

**Comment by andres-montanez** [comment]
Hi all, Version 1 of Magallanes has long reached it's end of life cycle, this feature will be available in the next mayor version.
Many thanks to all!
