### ISSUE TITLE
Documentation & contributor guidelines

### ISSUE THREAD

**Issue by jhuet** [andres-montanez/Magallanes#174]
I'm not sure this is the right place to start this up as there is a [MagallanesSite](https://github.com/andres-montanez/MagallanesSite) repository where the documentation is today but i feel like i'll have more feedback here, so here i am.

I wanted to start by saying i really like the [website](http://magephp.com/) it exposes very clearly the basics of how Mage works and how basic configurations can be done.

That said, it becomes a lot more frustrating when you're trying to use built-in tasks for example. As any _young_ project it is understandable that not everything is well documented and most people are used to go have a look at the code to have a better understanding of how it works. The problem for tasks is that they're not easy to read and more importantly it is difficult to see how they can be configured with specific parameters.

I'd like to help, hopefully with some task contributors, to improve this. What i see here is 2 different things to do :
1. __Documentation__ : It should be updated with the last PR's improvements and also each task contributor should also contribute to its documentation. We could provide a default template for a documented task to make it more easy.
2. __Contributor guidelines__ : We should encourage common good practices in order to have a consistent application. Today each contributed task is written a bit differently, there are arguments that are camel cased, others lower cased etc... Tasks code is not much documented either. This guide should address this so people reading the code could figure out more easily what it is doing. We shouldn't forget that we're dealing with deployment here, a very sensitive task when it comes to production. Users should easily find out how everything works.

To conclude, i feel that Mage is a very underestimated product and i think that contributing to these 2 things is going to definitely improve Mage adoption. That, and unit tests of course ;)

Any input on this ?

**Comment by eps90** [comment]
I agree, @jhuet 
Unit tests are on the way, testing environment is ready, we need to cover up existing code with tests. I had completly no time recently but I hope I'll come back into this soon. Any help will be appreciated ! :)

**Comment by jhuet** [comment]
As a start i propose we use a gist for the contributor guidelines. We'll be able to write the document and comment on it there : https://gist.github.com/jhuet/da204ccd1db2567cfc8b

**Comment by eps90** [comment]
Hmm, how about some Wiki page in Magallanes repo? Or even MD file in `docs`? Easier to maintain and advantages of versioning it with Git ;)

**Comment by jhuet** [comment]
Gist is versionized (it uses git behind the scene) and can be written in any language including MD. I felt like using this as long as the document is a draft to more easily enable people to contribute to it. It also allows comments so any back and forth discussion would be in one place with the document.

Then once we have something we think is good enough we could officially add it to the wiki or in a `docs` directory. What do you think ?

**Comment by eps90** [comment]
Just after adding my last comment, I got the same idea :) If there is a Git and we can see the history it's really great. the only disadvantage is that Gists don't support pull requsts...
Anyway, I'm in!
@andres-montanez What do you think about it?

**Comment by SenseException** [comment]
ping @andres-montanez

**Comment by DaniSancas** [comment]
Hi all,

I'm a watcher of this repo (good job, men, congratulations!) I'm tired of fighting against "crapifony", if you know what I mean. So, I'm migrating to Magallanes next week.

And here's my question: **Are you adding documentation about how to config Magallanes to share dirs and files?** From now it seems to be the only thing I miss in the already writen docs.

**Comment by jhuet** [comment]
@DaniSancas, yes that is definitely something that has to be documented too. In meantime, have a look at this [comment](https://github.com/andres-montanez/Magallanes/issues/156#issuecomment-68343018) i made, it should help you going about using symlinks to share directories.

**Comment by DaniSancas** [comment]
Great!!

I also found this other example https://github.com/andres-montanez/Magallanes/issues/75#issuecomment-52432284

My usual config in capifony is this (I think is the usual one)

    # shared files
    set :shared_files,    ["app/config/parameters.yml"]
    
    # shared children
    set :shared_children, ["app/logs", "app/sessions", "vendor", "web/uploads"]
    set :writable_dirs, ["app/cache", "app/logs", "app/sessions", "web/uploads"]

And, with your comment, and the comment I linked, I hope I can build a working config. I'll let you know in a few days if everything is working fine! Thanks for your support!!

**Comment by SenseException** [comment]
For constributions, we can use php-cs-fixer to keep consistency in coding style for contributions. We only need to find a fitting level for the fixer.

In case composer.json is going to be changed by a bugfix or a feature, we need to add how to build the composer packages to the documentation. Something like

```bash
php composer.phar update --prefer-lowest --prefer-stable
```

**Comment by eps90** [comment]
@SenseException Wake up :) Contribution guidelines has been made within #183 :)

**Comment by eps90** [comment]
@SenseException But I think `composer` usage should be a part of `README`, not contributor guidelines. I think that if someone is going to contribute, he knows how to install packages :)

**Comment by SenseException** [comment]
This can have a huge impact when packages are changing in a big way. Building up with other options can cause downloading newer, older or maybe dev packages that aren't stable.

**Comment by eps90** [comment]
Hey I've created a pull requests with some notes about testing coverage annotations to `CONTRIBUTING.md` file: #190

**Comment by eps90** [comment]
As the contribution document is ready, I've made an another detailed issue about dev documentation. Please take a look. I think that this issue is to close then :)
