### ISSUE TITLE
Deployment to localhost without ssh overhead

### ISSUE THREAD

**Issue by mabrahamde** [andres-montanez/Magallanes#182]
I am wondering if it would be possible to deploy a project to localhost without the overhead of ssh. 
I like the idea of executing magallanes directly on the server(s). In this case you do not need to connect via ssh. You can execute all commands directly.

I do not want to store the private keys on the server. Deploying from remote is not an option.

Any suggestions?

**Comment by eps90** [comment]
Have you tried `git-rebase` strategy?

**Comment by mabrahamde** [comment]
The git-rebase strategy does not seem to be a resolution.

I want to ping the server (solved outside of Magallanes). Then on the server Magallanes is called to deploy a new release, on itself. 

Magallanes should run on the servers directly.

**Comment by eps90** [comment]
Well there is no such functionality now, I think. Maybe I didn't notice it but you can of course use some simple workaround:
1. Create two environments - `prod` and `local`
2. Create simple task that would run magallanes deployment command with `local` environment as an argument
3. Configure `prod` environment to run your task on `on deploy` stage.

Nothing more comes into my mind in this moment.

PS. There exist an other way to do this, of course not out-of-the-box. I'm working on it and I'll open a pull request when it will be ready and tested.

**Comment by mabrahamde** [comment]
Thanks for your quick reply. I am looking forward to your pull request. :)

**Comment by TheRatG** [comment]
+1

**Comment by andres-montanez** [comment]
Hi, Version 1 of Magallanes has long reached it's end of life cycle, so no further changes will be integrated to it, focus is for the next next mayor version.
Many thanks!
