### ISSUE TITLE
Make Task-Factory more dynamic

### ISSUE THREAD

**Issue by Nilson89** [andres-montanez/Magallanes#188]
At the moment it is not possible to add new Tasks outside the .mage/task directory.

If you want to define Tasks to use in more than one project, you should be able to
1. Have a repository with composer support
2. Add this repository to projects dependencies in composer.json
3. Let the Task-Factory look for tasks like MyNamespace\Task\MyTask

**Comment by chrisfromredfin** [comment]
#189

**Comment by andres-montanez** [comment]
Hi, Version 1 of Magallanes has long reached it's end of life cycle, this feature will be available in the next mayor version.
Many thanks!
