### ISSUE TITLE
using git tag instead of timestamp for releases

### ISSUE THREAD

**Issue by alwex** [andres-montanez/Magallanes#192]
I think it would be very handy if we can combined magallanes with gitflow and use git tag to deploy a release.

for example I tag my master branch with v1.2.3, then I deploy this tag to production using

`bin/mage deploy --release=v1.2.3 to:dev`

Is there a workaround to make such a thing?

Really nice tool by the way.

**Comment by andres-montanez** [comment]
Interesting idea!
But we have to be careful, we can't introduce a feature "git dependent". 
Perhaps we could combine a scm task, and an option to overwrite the release id.

**Comment by eps90** [comment]
I like it too! :) But as @andres-montanez said, we can't be dependent only to one VCS. We should handle also other popular and still in use: Subversion, Mercurial, P4 and (eventually) CVS. But in the other hand a decorator implementing some `PackageReleaseAware` interface could do many other things, e.g. create a zip/tar file on target server.

**Comment by SenseException** [comment]
What does --release=v1.2.3 do when the code is executed? Are the release directories named by that parameter?
The deletion of old releases is coupled to the date-stamp it is using for the release directory names. We have to look for another deletion strategy in case we allow custom namings.

**Comment by alwex** [comment]
--release=v1.2.3 represent a git tag, in git flow you have to push a tag on your master branch to identify a release. Basically, this parameters will allow a `git checkout -f refs/tags/v1.2.3`

**Comment by SenseException** [comment]
@alwex Sounds interesting. Currently, I only know tag formats like you showed in your example (v1.2.3), but tags can have any format. We definitly would need another deletion-strategy for older releases when number of max releases is reached.

**Comment by alwex** [comment]
@SenseException of course, but I think that to be fully fonctionnal, the tag format may be fixed like MAJOR.MINOR.PATCH.

see for example the project https://github.com/Twenga/twgit which respect this versionning format.

**Comment by eps90** [comment]
Deleting old versions shouldn't be hard assuming that every release made by Magallanes in this case would be done by a `GitTagReleaseStrategy` (we can sort it using built-in `version_compare`). The problems shows up when target directory contains both timestamps and tag folders.
Other problem is lack of conditional deletion here. Someone would like to keep all the versions but get rid deprecated, unsupported ones.

**Comment by eps90** [comment]
@alwex Continuing your thought, how do you imagine to handle multiple releases of the same git-tag? The previous one should be removed? Let's say you need to deploy your app onto RC/QA server with certain tag and then you deploy it again. How should it behave? 
Something that comes into my mind at the moment is to pass another parameters to deploy strategy configuration to determine release id on target sever. What do you think?

**Comment by alwex** [comment]
@eps90, In my opinion, there is only one release by tag. Assume you create a package named `project-v1.0.1.tar.gz`, you can deploy it on all your environments without regenerating it.
If really needed, it is still possible to generate package like `project-v1.0.1-prod.tar.gz` etc...

**Comment by eps90** [comment]
Of course, but there must some solution what to do, when someone would like to do e.g.:
```bash
bin/mage deploy --release=1.2.3 to:dev
bin/mage deploy --release=1.2.3 to:dev
```
I don't know why and for whay but... what then? Should the old one be removed? The idea of current releases is to collect previous releases for safe rollback. If the previous tag-directory would be removed, you cannot rollback after unsuccessful deploy.
So I propose a solution: to create a timestamp directrory but prefixed with tag name, e.g.:
```
v1.2.3-beta_20150101120000
```

**Comment by eps90** [comment]
What do you think @alwex ?

**Comment by alwex** [comment]
I think you may have a look at [gitflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow), once a version is tagged, there is no further possible modifications to it. If you need to make a patch you use hotfixes and v1.2.3 goes to v1.2.4 with a new tag.

If you want to be able to deploy a the dev branch for example, then checkout this specific branch.

In my everyday work I use a script that is able to determine if I ask for a tag or a branch on git and the package will look like (I ask to deploy the branch master):

```
project-master.tar.gz
```

the name is [projectname]-[branch|tag].tar.gz

I don't think it is a good practice to deploy a not tagged version on production, so if we can assume that deploying a working branch is only for development purpose, is it interesting to keep track of the previous version? This will force people using git to correctly manage their deployment process.

What do you think?

**Comment by eps90** [comment]
Of course I see the advantages of your purpose but I was thinking about it in context of current deployment strategies. What you said make more sense now :) Would you like to keep old releases then anyway?

**Comment by alwex** [comment]
To keep the old releases then I think it can be interesting to tag them with the last commit id.
```
project-master-f1f457131897d2f13054861e8cc0b540a2830079.tar.gz
```
So it can be easy to rollback to previous version with a 
```
git checkout f1f457131897d2f13054861e8cc0b540a2830079
```
or to generate diff between two packages

**Comment by eps90** [comment]
Ok one more question - you've already given few examples with `*tar.gz` packages - is it part of your idea? To pack them and deploy as one file?

**Comment by alwex** [comment]
This is only because I am used to deploy tar.gz packages. I prefer to transfert one archive instead of rsyncing a lot of files to prevent network failure to break the production. If you use archive you are sure that there is no curruption during the transfert or whatever.

I use to deploy my project this way:

* checkout the git tag
* php lint on all php files
* composer install
* execute phpunit
* create the tar gz package
* generate MD5 checksum
* scp the package on all servers

then on each servers
* check the MD5 checksum against the tar.gz
* disable haproxy to get the serveur out of the pool
* extract the tar.gz eg: /var/www/project-v1.2.3/
* create the current symlink eg: /var/www/project-current => /var/www/project-v1.2.3/
* execute some tests scripts locally to check if everything is ok
* reload nginx/apache
* enable haproxy

**Comment by eps90** [comment]
Sure thing. Ok, I'll take a look on that but I'm not sure exactly when because I have little time recently but keep your eyes, ears and GitHub open :)

**Comment by alwex** [comment]
No problems, thank you for taking time to dig into this!

**Comment by andres-montanez** [comment]
Hi all, Version 1 of Magallanes has long reached it's end of life cycle, so no further changes will be integrated to it, focus is for the next next mayor version.
Certainly this is something I would like to add to the new version, but probably not in the first release. I will create an issue for this feature request.
Many thanks to you all!
