### ISSUE TITLE
Fix Version Information json for upgrade task

### ISSUE THREAD

**Issue by jtolj** [andres-montanez/Magallanes#198]
Looks like the same problem as this previous issue.
https://github.com/andres-montanez/Magallanes/issues/69

The trailing slash need to be removed from available[] in http://download.magephp.com/upgrade.json

Thanks!

**Comment by eps90** [comment]
I think you thought about trailing comma :)
Anyways, the issue is rather for https://github.com/andres-montanez/MagallanesSite, where the file belongs.

**Comment by andres-montanez** [comment]
Fixed! Many thanks! :)

**Comment by eps90** [comment]
Haha @andres-montanez , you was faster than me :D I've just made a PR :)

**Comment by andres-montanez** [comment]
That was crazy :D

**Comment by eps90** [comment]
Haha yeah  :D
