### ISSUE TITLE
StrictHostKeyChecking option inconsistently used?

### ISSUE THREAD

**Issue by kaiwa** [andres-montanez/Magallanes#202]
Is there any reason StrictHostKeyChecking=no is set for the `ssh` command but not for the `scp` command?

```
[18:29:51][Step 1/1] 2015-03-07 18:29:48 -- ---- Executing: $ ssh  -p 22 -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no teamcity@xxxxx "sh -c \"mkdir -p /var/www/xxx/releases/20150307182948\""
```
...
```
[18:29:52][Step 1/1] 2015-03-07 18:29:50 -- ---- Executing: $ scp  -P 22 /opt/teamcity-agent/temp/buildTmp/mage3Dm52H.tar.gz teamcity@xxxxx:/var/www/xxx/releases/20150307182948
[18:29:53][Step 1/1] 2015-03-07 18:29:50 -- Host key verification failed.
```

**Comment by eps90** [comment]
I don't know where does it came from, but I'm pretty sure this was added to prevent checking `known_hosts` in case you're connecting by SSH the first time:
```sh
The authenticity of host 'xxx.xxx.xxx.xxx (xxx.xxx.xxx.xxx)' can't be established.
RSA key fingerprint is f3:cf:58:ae:71:0b:c8:04:6f:34:a3:b2:e4:1e:0c:8b.
Are you sure you want to continue connecting (yes/no)? 
```
Have you got any problems with connection with that option?

**Comment by kaiwa** [comment]
Hmm yes but i don't see why the option is not set for both commands (ssh and scp) if it is set for one of them. If the host verification would have failed for the ssh command (but actually did not because of the StrictHostKeyChecking=no option) it will fail eventually for the scp command because it verifies the host too and the option is not set for that one.

I guess it makes only sense and is working as intended currently when using deployment strategies which do not use scp.

So i had no problem with the option beeing enabled, but because it was missing from the scp command. As you can see from the log lines I have posted, I got an "Host key verification failed" error for the scp command after the ssh command succeeded.

I were just wondering where the difference between both commands came from and I think they should behave the same way (both having ``-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no``).

But enabling host key verification might be the better choice anyway ;-)

//related #105

**Comment by eps90** [comment]
You're right, I haven't spotted that this options is missing for `scp` :) Surely it needs fixing to prevent this inconsistency. I'll try to make proper pull request today :) Maybe even with configuration from issue you related.
Thanks a lot! :)

**Comment by eps90** [comment]
@kaiwa Hey, I've made a pull request (#204) fixing your issue. Could you take a look on that and test it? If everything will be ok in your opinion, it's gonna be merged soon.

**Comment by kaiwa** [comment]
Tested it, works fine :+1: Thanks

**Comment by eps90** [comment]
Great, merging to develop then, will be released soon :)
