### ISSUE TITLE
RsyncTask - releasesDirectory checking issue

### ISSUE THREAD

**Issue by tychode** [andres-montanez/Magallanes#210]
Hi,

In file Mage\Task\BuiltIn\Deployment\Strategy\RsyncTask.php the statement can be seen:
```
if ($rsync_copy && is_array($rsync_copy) && $rsync_copy['copy'] && is_dir("$releasesDirectory/$currentRelease"))
```
This statement is always false. The function is_dir() checks whether path‘s $releasesDirectory/$currentRelease exist locally.

**Comment by andres-montanez** [comment]
Hi! Good point!
The new release takes care of this.

Many thanks!
