### ISSUE TITLE
Create repository for documentation

### ISSUE THREAD

**Issue by Trudko** [andres-montanez/Magallanes#212]
How about to create repo for documentation so people can contribute? I've spend good amount of time by figure how some stuff work and I am happy the little I've learned.

**Comment by eps90** [comment]
It's great idea to just **create** some detailed documentation. But why not to do it in this repo?

**Comment by Trudko** [comment]
Sure  why not :)  What would be the plan?

**Comment by eps90** [comment]
The thing is everyone's too lazy to start writing :D I'll collect necessary points to acheive and I'll make a new issue with *always-up-to-date* todo list. Then one would do it all or there will be pull requests with chapters (I'd recommend this one, shorter code review). I can't promise but I can prepare the list even today (if I find some spare time). Then you can be first to contribute if you said you found a lot of interesting things in code :) What do you think about such plan?

**Comment by eps90** [comment]
I've made an issue #213 with list of things to be documented. I think we can close this issue then?
