### ISSUE TITLE
Undefined variable: currentCopy

### ISSUE THREAD

**Issue by recchia** [andres-montanez/Magallanes#214]
when i try to execute a rollback fail because Undefined variable: currentCopy in file RollbackTask.php on line 140. I use magallanes 1.0.5

**Comment by eps90** [comment]
Yes this is known problem in latest release but it's already been fixed in #209 , so you can update Magallanes to `dev-master` in your `composer.json` file :)

**Comment by recchia** [comment]
Thanks for info, i will clone the repo cause im not use it as dependency in my project.

**Comment by eps90** [comment]
Cool, feel free to reopen this issue if bug presence is still up-to-date (I hope not :) )
