### ISSUE TITLE
Strategy git-rebase fails on releases.

### ISSUE THREAD

**Issue by JoaquinFB** [andres-montanez/Magallanes#216]
If you use git-rebase strategy with active releases, the timestamp release folder is created, but it's empty when finish all process...

I think that must to do a pull from repository git to have the last data.

So, command:
mage releases rollback --release=-1 to:production

This command leaves me the current folder referenced to a empty release.

Thank you.

**Comment by andres-montanez** [comment]
Hi @JoaquinFB , could you post your config? (exclude sensitive data)
So I can better reproduce the issue.

Thanks!

**Comment by JoaquinFB** [comment]
production.yml

#production
deployment:
  user: user
  from: ./
  to: /srv/www/htdocs/magento
  excludes:
  strategy: git-rebase 
releases:
  enabled: true
  max: 10
  symlink: current
  directory: releases
hosts:
  - 33.33.33.67
tasks:
  pre-deploy:
  on-deploy:
  post-release:
  post-deploy:



general.yml

# global settings
name: Magento
email: notifications@my.app
notifications: false
logging: true
maxlogs: 30
ssh_needs_tty: false

host 33.33.33.67 (/srv/www/htdocs/magento)  have a clone repository from git with folder (.git).
So changes when there are new commits on git it's ok!

But releases don't work:
/srv/www/htdocs/magento/releases/20150410100036 (it's empty)

May I be doing something wrong?

Thank you.

**Comment by eps90** [comment]
@JoaquinFB I change your comment formatting for better readability :)
Let me take a look on that. I'll give you feedback ASAP when I'll find what's wrong.

**Comment by MadMind** [comment]
The problem about releases + git-rebase is that it assumes the the newly created folder contains .git/ folder.

**Comment by MadMind** [comment]
@JoaquinFB to fix the issue add "repository" in your deployment parameters:

deployment:
  from: ./
  to: ./sites/test1
  strategy: git-rebase
  repository: git@github.com:my/test1.git

**Comment by JoaquinFB** [comment]
Ok, thank you.
