### ISSUE TITLE
fatal: Not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by recchia** [andres-montanez/Magallanes#219]
Best Regards,

When first release is done magallanes change branch to master always, in second release (i have set branch to dev in config) it fails showing message: fatal: Not a git repository (or any of the parent directories): .git. But nevertheless, if i change manually branch to dev before deploy it works fine.

**Comment by andres-montanez** [comment]
Hi, Version 1 of Magallanes has long reached it's end of life cycle, so no further changes will be integrated to it, focus is for the next next mayor version.
Many thanks!
