### ISSUE TITLE
error in packagist.org

### ISSUE THREAD

**Issue by Philou255** [andres-montanez/Magallanes#221]
I get the following error when using composer with the requirements "andres-montanez/magallanes": "*" 

 [RuntimeException]                                                                                                     
  Could not load package andres-montanez/magallanes in https://packagist.org: [UnexpectedValueException] Could not parse version constraint ^0.1: Invalid version string "^0.1"

**Comment by eps90** [comment]
That's odd, I've just created new project with Magallanes dependency as you typed (with asterisk) and it installed successfully. Try following things:
* Try to update composer by running `composer self-update`
* If you've already had Magallanes as a dependency, update the package to the newest vesion with `composer update andres-montanez/magallanes`
I've also noticed that `develop` and `master` had two different versions of `phpmock` library (on `develop` there actually was `^0.1` version) but I've just fixed it. So anyway, try to update composer and your dependency. Please tell us if that fixes your problem.

**Comment by andres-montanez** [comment]
Hi all, as @eps90 says, it's a very strange error. Specially because there isn't a "0.1" version.

**Comment by andres-montanez** [comment]
Hmmm, perhaps the error is from the phpmock dependency?

**Comment by eps90** [comment]
@andres-montanez For me installation with `"*"` and `"dev-develop"` as a version works fine.

**Comment by eps90** [comment]
@andres-montanez it's even more crazy - as far as I understand, @Philou255 declared Magallanes as a dependency, so composer should not install dev dependencies.

**Comment by andres-montanez** [comment]
¯\_(ツ)_/¯

**Comment by eps90** [comment]
I miss the "like" button on GitHub :)
@Philou255 Try to follow the steps from my first reply and tell us whether it helped you or not.

**Comment by eps90** [comment]
@Philou255 Any updates?

**Comment by Philou255** [comment]
Sorry it seems to be working now. Looks like our proxy is having issues with some requests.
