### ISSUE TITLE
Task: Copy vendors from previous release

### ISSUE THREAD

**Issue by marmotz** [andres-montanez/Magallanes#224]
@ramunasd has created issue #156, 6 months ago, and it was closed by responding that "you could use shared directories".

Yes. We could.
But, IMHO it's not a good practice because while you deploy a new release, vendors are updated and current release use the "new vendors".
If the deployment is successful, ~ ok. The time that the old release use new vendors is short.
But, when the deployment is a failure, current release use new vendors and we could have big problems.

So, I think it's a good idea to implement a new task to copy vendors from previous release.

**Comment by eps90** [comment]
Well, you might be right. But I think it could be resolved in the other way: by creating `on-rollback` or `post-rollback` hook. Here's why:
* you can link your `vendor` dir as usual, by creating shared links. `on-rollback` would execute once again `composer install` so previous vendors will come back to versions from old `composer.lock`
* sometimes we need to do other things on rollback. For example, rollback a DB migration, clear cache once a gain, and so on.

Of course `copy-vendors` task can be created as well :)

**Comment by marmotz** [comment]
Yeah, *-rollback was usefull !
But i think it's an other need and an other issue :)
Anyway, using *-rollback will not fix the short time lapse with a spatio-temporal flaw : old release use new vendors :)

**Comment by eps90** [comment]
Yep, that's true. I'll think about it and I'll try to write something soon. Or if you have working solution (or you want to do some) you can create a PR :) Thanks for suggestion anyway :)

**Comment by ramunasd** [comment]
Now i think this should be part of deployment strategy, not a separate task.

**Comment by eps90** [comment]
@ramunasd What, exactly?

**Comment by jhuet** [comment]
I kinda disagree on implementing this strategy about vendor on deployment by default. The good practice still is to always install vendor from `composer.lock` not to copy the old vendor.

**Comment by eps90** [comment]
Well, at first, it's not gonna be a part of strategy - it will be another task :)
```yaml
tasks:
  on-deploy:
    - composer/copy-vendors
    - composer/install
```
Then, there will be installed only **new** dependencies from `compose.lock`. If some dependency has been upgraded in `composer.lock`, it's gonna be installed too :)

**Comment by marmotz** [comment]
How to have access to last release in a task ?

**Comment by jhuet** [comment]
You can retrieve the actual release with `$this->getConfig()->getReleaseId()` as for the past ones, i'm not sure there is an easy way but you can get inspiration from [`ListTask`](https://github.com/andres-montanez/Magallanes/blob/master/Mage/Task/BuiltIn/Releases/ListTask.php#L34).

**Comment by andres-montanez** [comment]
Hi all, Version 1 of Magallanes has long reached it's end of life cycle, so no further changes will be integrated to it, focus is for the next next mayor version.
Many thanks to all!
