### ISSUE TITLE
Deployment "from:" location

### ISSUE THREAD

**Issue by mryanb** [andres-montanez/Magallanes#225]
If I specify a deployment location other than "./" a bunch of the commands fail. I am currently trying to specify "./my-git-repo"

**Comment by eps90** [comment]
Could you paste some logs?

**Comment by mryanb** [comment]
@eps90  The SCM commands were partially running.

Ex: This task pulls the from path so that it can be appended to commands
https://github.com/andres-montanez/Magallanes/blob/master/Mage/Task/BuiltIn/Scm/UpdateTask.php#L57

Ex: This task doesn't get the from path appended so it always runs in the root of the mage path.
https://github.com/andres-montanez/Magallanes/blob/master/Mage/Task/BuiltIn/Composer/InstallTask.php#L27

Logs: http://pastebin.com/RU3StbbP

**Comment by andres-montanez** [comment]
Hi all, Version 1 of Magallanes has long reached it's end of life cycle, so no further changes will be integrated to it, focus is for the next next mayor version.
Many thanks to all!
