### ISSUE TITLE
give help command on console

### ISSUE THREAD

**Issue by drAlberT** [andres-montanez/Magallanes#227]
running `mage` or `mage help` or `mage --help` or similar should give the user a command list or help ..

`Command "" not found.` or `Command "Help" not found.` is quite disorienting for new users ..

**Comment by eps90** [comment]
You're absolutely right. Some time ago I've started to build `--help` for all built-in commands but - don't remember why - I stopped. Recently I am extremely busy but I hope I'll finish what I've started.

**Comment by drAlberT** [comment]
:) thank you in advance then .. have a nice day

**Comment by eps90** [comment]
Good news, @drAlberT ! :)
I've found my old code with commands' help messages and I've decided it's ready to create some pull request with it (#228). You can look on it and tell what do you think. Unfortunatelly it doesn't include any help message for calling `mage` with no arguments. It's just help messages for commands. But I can promise I'll keep working on that :) Any feedback appreciated!

**Comment by drAlberT** [comment]
Very very nice  :+1:

**Comment by eps90** [comment]
As soon as the feature of commands help has been implemented (but it's not completed though) I think I can close the issue now. I hope the rest of commands will be documented soon :) Take care!

**Comment by drAlberT** [comment]
I hoped a "list all available commands" ...  ;(

**Comment by eps90** [comment]
Easy :) There are a lot of things to do and surely the list of available commands will be added :)

**Comment by drAlberT** [comment]
:+1:
