### ISSUE TITLE
bin/mage compatibility with php 5.3 / 5.4

### ISSUE THREAD

**Issue by dompie** [andres-montanez/Magallanes#229]
Hi,

just installed mage via composer using php53 (also tried php54). The following error occours:

```
PHP Fatal error:  Can't use function return value in write context in [...]Packages/Libraries/andres-montanez/magallanes/bin/mage on line 12
````

In php55 it's working fine. Please fix and release a new composer package. Packagist says, it should work with php >= 5.3 , but it's not.

**Comment by eps90** [comment]
Hey, I think it's already fixed in #220 but not released yet. You can check out `dev-develop` version :) I hope new version will come soon (there are few bugs to fix)
