### ISSUE TITLE
Environment variables in command execution

### ISSUE THREAD

**Issue by drAlberT** [andres-montanez/Magallanes#231]
Following #160 

I have a big big issue both with SSH and local commands ... I really need to be able to **replace** ENV not append ...  the reason?  Damned OSX :(

I have my env polluted by this variable `COM_GOOGLE_CHROME_FRAMEWORK_SERVICE_PROCESS/USERS/ALBERT/LIBRARY/APPLICATION_SUPPORT/GOOGLE/CHROME_SOCKET=/tmp/launch-DPIE9i/ServiceProcessSocket`

I googled a lot but found only other issues, no solution .. unset it seems impossible 

Moreover, I think the safer approach would be to pass only a very small set of env variables in the command to be executed .. having the ability to add some custom values (you just implemented) will allow to add any exotic var one can need

This could concern security too .. as SSH can pass only some env vars, so we should do :)

**Comment by drAlberT** [comment]
Update:

`putenv('COM_GOOGLE_CHROME_FRAMEWORK_SERVICE_PROCESS/USERS/ALBERT/LIBRARY/APPLICATION_SUPPORT/GOOGLE/')` into `bin/mage` and  the incrimined env var was gone (just to test)

The problem still persist .. now PATH is giving the same issue .. I think this is a Mac OS X problem .. going to try port's bash

**Comment by drAlberT** [comment]
`PS1=\h:\W \u\$`  => `sh: u$: command not found`

Ok it seems there is a big issue with command execution on OS X .. some escaping is needed

**Comment by eps90** [comment]
Hi @drAlberT 
That's interesting. Command escaping has been already made (I've merged a PR today but I am not sure whether it covers all cases) but I was sure that modifying env variables by passing them before command call should be done successfully anyway. I need to look deeper into it.

**Comment by drAlberT** [comment]
I think the right approach should be to pass to command only a few set of really needed ENV, not all the environment (say TERM, LC_ and so on ..)

**Comment by andres-montanez** [comment]
Hi, Version 1 of Magallanes has long reached it's end of life cycle, so no further changes will be integrated to it, focus is for the next next mayor version.
Many thanks!
