### ISSUE TITLE
Command line execution issues

### ISSUE THREAD

**Issue by drAlberT** [andres-montanez/Magallanes#237]
Both local and remote commands has to be analysed in deep in order to double check command name / arguments escaping (i.e. be sure to escape every command or argument injection .. btw, nowadays mage runs remotely as _root_)

Furthermore when chown fails (for example) it is very hard to argue the root reason as the output given on commands execution is even too verbose on success but poor on remote errors ..

Again, I think we should think about the use of sprinf() to format the command line in the code, in order to minimise the huge string concatenation that is widely used nowadays and that makes the code hard to read and debug .. 

My 2 cents ;)

see #232

**Comment by eps90** [comment]
Hi @drAlberT , thanks for opening that issue. Please confirm, that #232 has to be reverted.
What do you mean by saying the following?
> nowadays mage runs remotely as root

**Comment by drAlberT** [comment]
Hi

#232 as it is makes almost every command to fail .. So yes, it can't be merged this way 


I mean that to run "chown" (and it is hardcoded on deploy), to be able to delete old revisions (where www user has written logs and cache and own these files) and so on I think that the "deploy user" should be root or some privileged user ..

In my case I deploy as webmaster, apache is www-data and set this as owner but I can't have Mage to success unless I tweak it to skip such commands or run via sudo ...

Hope to have been much clear :)))

**Comment by kuborgh-mspindelhirn** [comment]
At least for rsync strategy it seems like simply not escaping the output streaming would fix #232 

Current state:
```
exec(escapeshellcmd($command . ' 2>&1'), $log, $return);
```

This works for me:
```
exec(escapeshellcmd($command) . ' 2>&1', $log, $return);
```

**Comment by kuborgh-mspindelhirn** [comment]
Ok. Most tasks chain commands with && and escapeshellcmd breaks the chain silently so that is an other issue. Would be great if the pull request could be reverted.

**Comment by gwilgen** [comment]
Hi! I'm taking a wild guess addressing here a problem I've found:

I'm using cygwin, and in my first deploy, I notice that every command fails with the following sentence:
`bash: -c: line 0: unexpected EOF while looking for matching `"'`

I edited **Task/AbstractTask.php** (line 209 in current release) and replaced
`$localCommand .= ' ' . '"sh -c \"' . $remoteCommand . '\""';`
with
`$localCommand .= ' "sh -c $(' . $remoteCommand . ')"'; `

hope that helps!

by the way, I didn't have rsync in the server, it would be useful to propagate the error result to the mage command

**Comment by andres-montanez** [comment]
Hi, Version 1 of Magallanes has long reached it's end of life cycle, so no further changes will be integrated to it, focus is for the next next mayor version.
Many thanks!
