### ISSUE TITLE
Custom task was not found

### ISSUE THREAD

**Issue by eaglefsd** [andres-montanez/Magallanes#246]
Heyho,

I'm trying to fix my permissions with a custom task.

My code looks like this:

``` php
namespace Task;

use Mage\Task\AbstractTask;

class Permissions extends AbstractTask
{
    public function getName()
    {
        return 'Setze Berechtigungen auf 775';
    }

    public function run()
    {
        $command = 'chmod -R 775 /path/to/directory';
        $result = $this->runCommandRemote($command);

        return $result;
    }
}
```

The file is called Permissions.php and it is stored in .mage/tasks.
I call the task with `- permissions`.

Magallanes always tells me that "Task Permission was not found". What am I doing wrong?

**Comment by benr77** [comment]
I have the same issue. Custom task set up and working correctly on 1.0.3

Upgraded to 1.0.4, 1.0.5 or 1.0.6 and suddenly the custom tasks cannot be found. Roll back to 1.0.3 and they are executed correctly again.

**Comment by pfastre** [comment]
Same issue here. 1.0.3 works, 1.0.6 not.

**Comment by tilt86** [comment]
Idem for me with 1.0.6. Not tested with version < 1.0.6

**Comment by 501c3** [comment]
I also find the exact same issue with 1.0.6.  Some notes:
I installed magellanes in /opt/magellanes according to the instructions for a system wide installation in the first couple of paragraphs of the website....

**Comment by marcocarnazzo** [comment]
Same issue with 1.0.6.
As a workaround I converted MyCustomTask into a builtin task.

**Comment by tilt86** [comment]
I used this repo https://github.com/magephp/magallanes and it works.

**Comment by Amzani** [comment]
I found a workaround @eaglefsd 

Use this :
```{r, engine='bash'}
tasks:
     on-deploy:
        - scm/force-update
        - general/manually:
           - chmod -R 775 /var/www/vhosts/hassels.eu/schule.hassels.eu/
```

**Comment by Amzani** [comment]
@tilt86 what's the # btw  https://github.com/magephp/magallanes  and this repo ?

**Comment by 1ma** [comment]
@andres-montanez @eps90 & to whom it may concern, I've submitted a PR to fix this issue. I'd be nice to have a hotfix release.

**Comment by andres-montanez** [comment]
Hi all the PR has been merged, also Version 1 of Magallanes has long reached it's end of life cycle, and this feature will be available in the next mayor version and will be even better, taking full advantage of Composer.
Many thanks to all!
