### ISSUE TITLE
applyFaclsTask inaccessible

### ISSUE THREAD

**Issue by dompie** [andres-montanez/Magallanes#251]
How you can use applyFaclsTask?

I tried 
- filesystem/apply-facls-task 
- apply-facls-task

according to PermissionsTask documentation. But it says all time: Task "BuiltIn/filesystem/applyFaclsTask" not found.

And documentation ist _not_`present for ApplyFaclsTask.

Can anyone help?

**Comment by drAlberT** [comment]
use `filesystem/apply-facls` (without "task")

**Comment by andres-montanez** [comment]
Hi, Version 1 of Magallanes has long reached it's end of life cycle, so no further changes will be integrated to it, focus is for the next next mayor version.
Many thanks!
