### ISSUE TITLE
Enable sending copy email after deployment (addCC)

### ISSUE THREAD

**Issue by proxium** [andres-montanez/Magallanes#252]
Hello,

I checked Magallanes to see if I can use CC parameter and specify it in general.yml but I didn't found any existing implementation for that feature. Actually I'm using two email address in email field (general.yml):
email: email1@domain.me, email2@domain.me

It would be great to specify headers option with email

**Comment by csuarez** [comment]
Implemented in #296

**Comment by andres-montanez** [comment]
Hi, Version 1 of Magallanes has long reached it's end of life cycle, so no further changes will be integrated to it, focus is for the next next mayor version.
Many thanks!
