### ISSUE TITLE
Per Host Configuration - YAML 

### ISSUE THREAD

**Issue by dariuszjastrzebski** [andres-montanez/Magallanes#256]
I wanted to use a different host configruation and in documentation in section : "Per Host Configuration" is example:

<pre>
hosts:
    - 172.16.0.101
    172.16.0.102:
        deployment:
            to: /home/sites/example.com/www
            user: legacy
        releases:
            max: 5
            symlink: httpdocs
        tasks:
            on-deploy:
                - custom-cache-warmup
    - 172.16.0.201:2222
</pre>

This example is <span style="color:red">not correctly parsed</span> the yaml ( You cannot define a mapping item when in a sequence)
maybe it should be:

<pre>
hosts:
    - 172.16.0.101
    - 172.16.0.102:
</pre>

???

and how can I overwrite configurations for host with other port ? 
e.g.

<pre>
hosts:
    - 172.16.0.102:8089:
        deployment:
            to: /some/other/path
            user: other_user
    - 172.16.0.101
</pre>

but this doesn't work . It's trying "Deploying to 0" ??
I can create two deployments but why if it's the same deploy.

**Comment by psren** [comment]
At least i can confirm the problem. Per host configuration doens't seem to work like mentioned in the docs

**Comment by arielkung** [comment]
To solve the problem in yaml the conf should be like this:

```
hosts:
    172.16.0.102:8089:
        deployment:
            to: /some/other/path
            user: other_user
    172.16.0.101: {}
```

Documentation needs to be updated I think.

**Comment by psren** [comment]
Yop. Works like a charm :+1:
