### ISSUE TITLE
Replace default rsync args deployment

### ISSUE THREAD

**Issue by sfi-fgarnier** [andres-montanez/Magallanes#259]
[production.yml]
strategy: rsync
strategy_flags: # additional strategy options
    rsync: '--checksum --stats --omit-dir-times --ignore-times --delete --delete-after'

By default, "archive mode" is activated in the rsync way deployment (rsync -avz ...), how am I supposed to do if I want to remove "archive mode" or replace some args (-a -v -z) and deploy like this "rsync -rlgvz ..." instead of "rsync -avz ..." ?

**Comment by andres-montanez** [comment]
Hi, Version 1 of Magallanes has long reached it's end of life cycle, this feature will be available in the next mayor version.
Many thanks!
