### ISSUE TITLE
Can't run Magallanes globally

### ISSUE THREAD

**Issue by lukashillebrand** [andres-montanez/Magallanes#266]
Hi, thanks for making  Magallanes!
it runs very good with composer on a project basis, but not globally on my system, maybe there's hope :)
1. Installed succesfully http://bit.ly/1RXbKMJ
2. Added PATH to .bash_profile: `export PATH="$HOME/.composer/vendor/bin:$PATH"`
3. Error: http://bit.ly/1RXc52b

Any suggestions? Thanks!

**Comment by andres-montanez** [comment]
Hi, Version 1 of Magallanes has long reached it's end of life cycle, so no further changes will be integrated to it, focus is for the next next mayor version.
Many thanks!
