### ISSUE TITLE
Deployment parsing error

### ISSUE THREAD

**Issue by tilt86** [andres-montanez/Magallanes#267]
Hello,

I installed mage through composer, in composer.json:

>  ...
>    "require-dev": {
>        "andres-montanez/magallanes": "dev-develop"
>   },
> ....

then 

> composer.phar update andres-montanez/magallanes
> ###### 

It installed well:
root@test:/home/lprik/test# bin/mage version

> Running Magallanes version 1.0.6
> ###### 

I then initialized:
lprik@test:~/test$ bin/mage init --name="magetest atr" --email=luc.prik@gmail.com

>   Starting Magallanes
> 
>   Initiating managing process for application with Magallanes
>   Success!! The configuration for Magallanes has been generated at .mage directory.
>       Please!! Review and adjust the configuration.
> 
>   Finished Magallanes
> ###### 

.. and added an env:
lprik@test:~/test$ bin/mage add environment --name="preproduction"

>   Starting Magallanes
>   Logging enabled: /home/lprik/test/.mage/logs/log-20151117-141920.log
> 
>   Adding new environment: preproduction
>   Success!! Environment config file for preproduction created successfully at /home/lprik/ren_atr-site/.mage/config/environment/preproduction.yml
>       So please! Review and adjust its configuration.
> 
>   Finished Magallanes
> ###### 

The file for deployment: .mage/config/environment/preproduction.yml 

> # preproduction
> 
> deployment:
> user: lprik
>  identity-file: /home/lprik/.ssh/id_rsa
> from: ./
>  to: /home/lprik/preprod
> excludes:
> hosts:
>  localhost
> tasks:
>  pre-deploy:
> on-deploy:
>  post-deploy:

(I also tried with with strategy: rsync and targz, and with a remote working server 192.168.1.1)
###### 

But when I run the deploy command, it fails...
lprik@test:~/test$ bin/mage deploy to:preproduction

> Starting Magallanes
>   Logging enabled: /home/lprik/test/.mage/logs/log-20151117-142159.log
> 
>   Deploy summary
>       Environment: preproduction
> 
>   No Pre-Deployment tasks defined.
> 
>   Deploying to localhost
>       Running Deploy via Rsync [built-in] ... Unexpected remote arg: >lprik@localhost:/home/lprik/preprod
> rsync error: syntax or usage error (code 1) at main.c(1348) [sender=3.1.1]
> FAIL
>   Deployment to localhost completed: 0/1 tasks done.
> 
>   A total of 1 deployment tasks failed: ABORTING
> 
>   No Post-Deployment tasks defined.
> 
>   Time for deployment: 0 seconds.
>   Average time per host: 0 seconds.
>   Total time: 0 seconds.
> 
>   Command execution failed with following exit code: 1
> 
> Finished Magallanes
> ###### 

the log file:

> 2015-11-17 14:41:11 -- Starting Magallanes
> 2015-11-17 14:41:11 -- Logging enabled
> 2015-11-17 14:41:11 -- Logging enabled: /home/lprik/test/.mage/logs/log-20151117-144111.log
> 2015-11-17 14:41:11 -- Deploy summary
> 2015-11-17 14:41:11 -- Environment: preproduction
> 2015-11-17 14:41:11 --
> 2015-11-17 14:41:11 -- No Pre-Deployment tasks defined.
> 2015-11-17 14:41:11 -- Deploying to 192.168.1.1
> 2015-11-17 14:41:11 -- Running Deploy via Rsync [built-in] ...
> 2015-11-17 14:41:11 -- ---------------------------------
> 2015-11-17 14:41:11 -- ---- Executing: $ rsync -avz  --rsh="ssh -i /home/lprik/.ssh/id_rsa -p22" -->exclude='.git'  --exclude='.svn'  --exclude='.mage'  --exclude='.gitignore'  --exclude='.gitkeep'  -->exclude='nohup.out'  ./ lprik@192.168.1.1:/home/lprik/preprod
> 2015-11-17 14:41:11 --
> 2015-11-17 14:41:11 -- ---------------------------------
> 2015-11-17 14:41:11 -- FAIL
> 2015-11-17 14:41:11 -- Deployment to 192.168.1.1 completed: 0/1 tasks done.
> 2015-11-17 14:41:11 -- A total of 1 deployment tasks failed: ABORTING
> 2015-11-17 14:41:11 -- No Post-Deployment tasks defined.
> 2015-11-17 14:41:11 -- Time for deployment: 0 seconds.
> 2015-11-17 14:41:11 -- Average time per host: 0 seconds.
> 2015-11-17 14:41:11 -- Total time: 0 seconds.
> 2015-11-17 14:41:11 -- Command execution failed with following exit code: 1
> 2015-11-17 14:41:11 -- Finished Magallanes
> ###### 

If I execute the command directly, it works:
lprik@test:~/test$ rsync -avz  --rsh="ssh -i /home/lprik/.ssh/id_rsa -p22" --exclude='.git'  --exclude='.svn'  --exclude='.mage'  --exclude='.gitignore'  --exclude='.gitkeep'  --exclude='nohup.out'  ./ lprik@localhost:/home/lprik/preprod

> sending incremental file list
> ./
> vendor/f......
> .....
###### 

And with targz, I have this:

> ```
>   Running Deploy via TarGz [built-in] ... tar: 2>&1: Cannot stat: No such file or directory
> ```
> 
> tar: Exiting with failure status due to previous errors
> 2>&1: No such file or directory
> tar (child): mageoMPgFQ.tar.gz 2: Cannot open: No such file or directory
> tar (child): Error is not recoverable: exiting now
> tar: Child returned status 2
> tar: Error is not recoverable: exiting now
> FAIL
> ###### 

I don't understand if I made something wrong somewhere, configuration file, mage develop branches, a tool I miss on the system...?

Thanks

**Comment by tilt86** [comment]
I managed to make it work, switching from dev-develop to 1.0.1
But in fact, I was with php < 5.5 first, and to make it work I changed this in bin/mage.

$timezone = ini_get('date.timezone');
if (empty($timezone)) {
#if (empty(ini_get('date.timezone'))) {
    date_default_timezone_set('UTC');
}

now it works with all php version on master branch with this change.

**Comment by andres-montanez** [comment]
Hi, Version 1 of Magallanes has long reached it's end of life cycle, so no further changes will be integrated to it, focus is for the next next mayor version.
Many thanks!
