### ISSUE TITLE
switching symlink atomically

### ISSUE THREAD

**Issue by vlcekmi3** [andres-montanez/Magallanes#271]
What about flip the symlink atomically by creating a temporary one and renaming it with `mv -T`?
as mentioned here: https://codeascraft.com/2013/07/01/atomic-deploys-at-etsy/

`ln -s new current_tmp && mv -Tf current_tmp current`

**Comment by jhuet** [comment]
I think you should leave it open. There's not much activity here lately but atomic symlinking should definitely get into Magallanes.

**Comment by vlcekmi3** [comment]
yes, i agree, but i realized that this feature is already done..

look at: https://github.com/andres-montanez/Magallanes/blob/master/Mage/Task/BuiltIn/Deployment/ReleaseTask.php#L87

**Comment by jhuet** [comment]
:+1:
