### ISSUE TITLE
Check if "chown" is available"

### ISSUE THREAD

**Issue by georgringer** [andres-montanez/Magallanes#273]
on some hosters, the command "chown" is not supported. Therefore it must be checked if it is there, otherwise no deployment is possible with magallanes

I did a pull request already: https://github.com/georgringer/Magallanes/commit/cb125b63cdcd827dce984704c7568eb6cf97ab8e

would be more than happy to get feedback

**Comment by misterboe** [comment]
+1

**Comment by AndreasA** [comment]
Btw. I think mage actually currently has a bug:
If one sets owner then releases will not set fetchResult and ignore user/group settings.

**Comment by andres-montanez** [comment]
Hi, Version 1 of Magallanes has long reached it's end of life cycle, so no further changes will be integrated to it, focus is for the next next mayor version.
Many thanks!
