### ISSUE TITLE
Deploying with different branch with git-rebase strategy

### ISSUE THREAD

**Issue by diegorodrgrapa** [andres-montanez/Magallanes#275]
Trying to set up Magallanes (1.0.6), I've encountered a problem trying to deploy with git-rebase strategy: it always deploys using the branch master.
I'd like to deploy to a develop environment using a different branch, say "dev". Is there any way to do this? 

I've checked Magallanes code and I've seen that in GitRebaseTask.php file it looks for a parametre branch, and if there is none it uses the branch master:

``` php
$branch = $this->getParameter('branch', 'master');
```

So in theory it should be possible to indicate which branch we want to use, but can't find the way to pass the parameter there.

Any suggestions / help? Thank you.

**Comment by kurtec** [comment]
I've encountered the same problem
You can solve this by adding command line option
```bash
mage deploy to:production --branch=branch_name
```

**Comment by diegorodrgrapa** [comment]
Wow, couldn't work out that it worked that way!! Thanks a lot, will try it soon.

Cheers.

**Comment by andres-montanez** [comment]
Hi, Version 1 of Magallanes has long reached it's end of life cycle, so no further changes will be integrated to it, focus is for the next next mayor version.
Many thanks!
