### ISSUE TITLE
[FEATURE] copy "current" release to a fix path (opcache / pathcache)

### ISSUE THREAD

**Issue by AndreasA** [andres-montanez/Magallanes#280]
Some servers might have troubles if the destination folder (current) is a link, it is not that problematic if it is the final destination but sometimes one only creates a link to the current folder inside the docroot.

On some servers I had problems that the end destination of files was not updated correctly (even if doing a manual opcache clear it didn't always work, maybe due to threading or load-balancing over multiple servers).

**Comment by andres-montanez** [comment]
Hi, Version 1 of Magallanes has long reached it's end of life cycle, so no further changes will be integrated to it, focus is for the next next mayor version.

I had a similar issue with OPCache and APC, so I've added a post release task with a reload of the php-fpm o webserver to make sure memory is wiped out.

Many thanks!

**Comment by AndreasA** [comment]
Still would like to see such a feature in v2.
Also php-fpm might not be used (or reload might require permissions that don't exist), so I still think a copy option would be nice.

**Comment by andres-montanez** [comment]
Hi! I've created the issue #319 in order to add this feature in the new road map.

Cheers!
