### ISSUE TITLE
If the logs folder is missing, mage command just spits out a bunch of errors

### ISSUE THREAD

**Issue by mattsnowboard** [andres-montanez/Magallanes#282]
The error here:
PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/project/vendor/andres-montanez/magallan
es/Mage/Console.php on line 235

Could be prevented by printing a more useful message when the fopen fails to open a file.

**Comment by dn5** [comment]
The better fix would be to automatically create `logs` folder in case it failed to look for it.

**Comment by andres-montanez** [comment]
Hi all, Version 1 of Magallanes has long reached it's end of life cycle, in the next mayor version logs are optional.
Many thanks to all!
