### ISSUE TITLE
Support for additional ssh options

### ISSUE THREAD

**Issue by kuborgh-hgiesenow** [andres-montanez/Magallanes#289]
I need support for additional ssh options. For my case i need to specifiy a `-o ProxyCommand="ssh ..."`. This should be used for ssh, scp and rsync.
I will try to provide a PR.

**Comment by andres-montanez** [comment]
Hi, Version 1 of Magallanes has long reached it's end of life cycle, so no further changes will be integrated to it, focus is for the next next mayor version.
Many thanks!
