### ISSUE TITLE
chown not executed in ReleaseTask if owner is set

### ISSUE THREAD

**Issue by AndreasA** [andres-montanez/Magallanes#304]
In the current ReleaseTask if one has set the owner option then chown will not be executed due to fetchResult never being set.

https://github.com/andres-montanez/Magallanes/blob/dd79eca75f8bc5ee1f970ad5853c3fa1df96e0fd/Mage/Task/BuiltIn/Deployment/ReleaseTask.php#L52

Which is only set in line 62 if $userGroup is empty which it isn't if owner is set.
However, if you fix this do only so in combination with:
https://github.com/andres-montanez/Magallanes/issues/273

Because currently it is a good workaround for that issue :)

**Comment by andres-montanez** [comment]
Hi, Version 1 of Magallanes has long reached it's end of life cycle, so no further changes will be integrated to it, focus is for the next next mayor version.
Many thanks!
