### ISSUE TITLE
Windows problem

### ISSUE THREAD

**Issue by matiux** [andres-montanez/Magallanes#306]
I have a problem to deploy from windows.

I get this error when tar runs:

tar<child>: Cannot connect to C: resolve failed  

I have read that the reason is that tar interprets colons (:) in file names as meaning it is a file on another machine. tar has the --force-local option that solve this problem if I run the commnad manually in terminal

But how can I apply this option to magellan task?

**Comment by andres-montanez** [comment]
Hi, Version 1 of Magallanes has long reached it's end of life cycle, so no further changes will be integrated to it, focus is for the next next mayor version.
Many thanks!

**Comment by fritzmg** [comment]
It can be fixed by using
```
tar_create: cfzop --force-local
```
for example (_cfzop_ is the default for `tar_create`).
