### ISSUE TITLE
Magallanes can't delete old releases: Permission denied

### ISSUE THREAD

**Issue by marcocarnazzo** [andres-montanez/Magallanes#308]
It's not a bug but I have a problem.
Magallanes can't delete old releases: "www-data" wrote files into cache directories and deployer user doesn't own them.

How do you resolve this matter?
Thank you.

**Comment by baldy2811** [comment]
Config your Apache that he acts as deployer user. Mostly done in php-fpm or fcgi - it depands on what you use
