### ISSUE TITLE
runCommand* to return output instead of bool

### ISSUE THREAD

**Issue by dn5** [andres-montanez/Magallanes#310]
The `runCommand` and `runCommandRemote` returns boolean value whether the command was executed successfully. Is there a way to return an output/stdout of the command instead.
  
Pseudo Scenario: 
You want to return **sha-1** of the file from previous release and compare it with the **sha-1** of the file from current release being deployed.

Example:
```
<?php
   $x = $this->runCommandRemote('cd /rollback/olderversion/ && sha1sum file.txt') // return sha1 sum from remote
   $y = $this->runCommand('sha1sum file.txt') // return sha1 sum from current release

   ...

   if ($x != $y) { 
       return do_something_else();
   }

   return do_something();
```

**Comment by aschempp** [comment]
You can use the second argument to `runCommand` to get the output: https://github.com/andres-montanez/Magallanes/blob/master/Mage/Task/AbstractTask.php#L169

**Comment by dn5** [comment]
You are right. Totally missed that the parameter is referenced, though it was for other operation.
