### ISSUE TITLE
[Task] Hard Current

### ISSUE THREAD

**Issue by andres-montanez** [andres-montanez/Magallanes#319]
Create a task for creating a hard copy of the current release besides the `current` symlink.
Most probable solution will be to copy the released directory to `releases/current` so all symlinks inside will still work.
The `current` symlink must still exists in order to know which one is the current release.

Feature Request derived from #280

**Comment by AndreasA** [comment]
Hi, 
just wondering do you have an expected implementation date for this feature?

**Comment by andres-montanez** [comment]
Won't do.
