### ISSUE TITLE
Composer path configuration per Environemt

### ISSUE THREAD

**Issue by ufeldmann** [andres-montanez/Magallanes#329]
Wouldn't it be better to set the individual composer path per environment instead of setting it globally?

**Comment by andres-montanez** [comment]
Hi!
Ideally composer would be installed globally, but I understand that's not always the case, so yes, it makes sense to allow a per environment option too.
Thanks! I will try to squees this on the next release.

**Comment by Toflar** [comment]
Same here, this is a big problem. The environments might also be split over different hosts or physical servers so this is really need. I [quickly created a PR](https://github.com/andres-montanez/Magallanes/pull/330) for this, hoping that new versions will be released more often than in the past ;-)

**Comment by andres-montanez** [comment]
Hi @Toflar , thanks for the PR, I will take a look at it!
And yes, the idea is to release more often :D

**Comment by Toflar** [comment]
Merged for v3.1, can be closed ;)

**Comment by andres-montanez** [comment]
3.1 will be released end of the month, luckily this is the shortest month! ;)
