### ISSUE TITLE
v3 FTP / SFTP gone?

### ISSUE THREAD

**Issue by MM-Psiiirus** [andres-montanez/Magallanes#334]
Is there still a way to use an ftp connection with mage?

**Comment by andres-montanez** [comment]
Hi @MM-Psiiirus, there are many features in V1 that are not present in V3.
The idea now is to have a better Core and add features more slowly and 100% tested.

So for now there is no way to use FTP/SFTP. Still I strongly recommend not to use it, given that the FTP is an unsafe protocol. If you can the SSH then you use it for rsync or scp.

Regards.
