### ISSUE TITLE
Provide a pre-build mage.phar executable

### ISSUE THREAD

**Issue by thePanz** [andres-montanez/Magallanes#337]
I'd like to use mage not as a library, but as a deployment tool. Thus not requiring `mage` in my composer dependencies (what if I use symfony2 and can't upgrade to symfony3?)

I'll provide a first support for Box (https://box-project.github.io/box2/) as I already have a first working example :)

**Comment by andres-montanez** [comment]
HI @thePanz a box file would be great!
Also currently I'm reviewing about installing Magallanes as a global command, using composer global, that should cover using mage without requiring it in the project :)

**Comment by thePanz** [comment]
Hola Andres! My plan is to have a self-contained phar, which does not require any other command/library to be executed. As you can imagine, adding magelan to the "global" would raise the same issue about dependency compatibilities :)

**Comment by andres-montanez** [comment]
Yes, but the global require will not conflict on your project, only if you have other tools globally installed with conflicting versions.

How will be generated the phar? That's my main concern :)

**Comment by thePanz** [comment]
Globals: yes, and you never know what a user has a global ;)

The phar: give it a try to the PR :)
The main process is able to run, even I'm facing some issue in finding the `.mage.yml` configuration (using a `$mage = new MageApplication(realpath('.mage.yml'));` in `bin/mage:14` helped

btw: I am not able to get any log using `-vvv`, nor any logs (even after setting `magephp: log_dir:` conf)
