### ISSUE TITLE
Add a "--dry-run" option

### ISSUE THREAD

**Issue by thePanz** [andres-montanez/Magallanes#339]
As a developer, I'd like to have an option to simulate the deployment

**Comment by andres-montanez** [comment]
Hi, I totally agree, it's a cool option.
But due the nature of the application, which heavily relies on command output (eg: list directories, run git commands, etc), the effort required for the feature is to big for the current scope of the project.

I will cose the issue but probably will revisit it in a future version.

Thanks!
