### ISSUE TITLE
Allow `fs/remove` to remove folders

### ISSUE THREAD

**Issue by thePanz** [andres-montanez/Magallanes#340]

**Comment by mbaeuerle** [comment]
I used a kind of hack to delete directories: 
```
        - fs/remove: { file: '-r public_bak' }
```

**Comment by thePanz** [comment]
Nice, I guess it could be considered a "bug" as the filename is not escaped during the command execution :)

**Comment by mbaeuerle** [comment]
Let's call it a helpful bug 😋

**Comment by andres-montanez** [comment]
LOL, "it's not a bug, it's a feature"
