### ISSUE TITLE
Verbose mode doesn't show errors from executed commands

### ISSUE THREAD

**Issue by mbaeuerle** [andres-montanez/Magallanes#343]
I really enjoy using Magallanes, the overall process is very easy!
 
Most of the issues were external commands like `composer` or `cp`. 
But unfortunately there is no information of what went wrong:

```        
Running [FS] Copy "public_bak/*.*" to "public/" ... FAIL
Finished 6/9 tasks for On Deploy.


Stage "On Deploy" did not finished successfully, halting command.
```
I had to ssh into my deployment server and run the command manually to see the actual error. I thought the `-v` mode would show more, but it doesn't.

**Comment by andres-montanez** [comment]
Hi, if you enable the logs, you will see there all that's being done in the background, and also the responses from those commands.
That log should be very helpful for investigating what's going wrong.

**Comment by mbaeuerle** [comment]
Ah well I should have read the docs more carefully, shame on me.
