### ISSUE TITLE
Update require-dev phpunit to 5.x 

### ISSUE THREAD

**Issue by mbaeuerle** [andres-montanez/Magallanes#345]
Is there a specific reason why phpunit 4.8.x is used? 
Version 5 adds quite nice features like:
``` php
$this->expectException(ErrorException::class);
$this->expectExceptionMessage('Parameter "file" is not defined');
```

**Comment by andres-montanez** [comment]
Yes, PHPUnit 5 and above require PHP 5.6, and changing that will break compatibility with Symfony 3 which requires PHP 5.5.9.

End of the year Symfony 4 will be released with a PHP requirement of >= 7 ;)

**Comment by mbaeuerle** [comment]
Symfony achieved php 7 compatability [2 years ago](http://symfony.com/blog/symfony-achieves-100-php7-compatibility)!
PHP 5.5.9 is the minimum required version! So it should be fine to upgrade!

**Comment by andres-montanez** [comment]
Yes, but the require is still in the dependencies, so you can run Symfony3 with php 5.5.9+, that should be maintained here in order to allow those users to use Magallanes.

**Comment by mbaeuerle** [comment]
Ah okay, so the issue is not Symfony but the version of php. So you want to maintain php 5.5.9 as the minimum requirement for Magallanes as long as possible?

**Comment by andres-montanez** [comment]
Exactly, I want to maintain the same minimum requirements as Symfony3.
And I hope most of those who uses Magallanes have newer versions, I still want to maintain the most compatibility, that's also why Travists tests are run against 5.5, 5.6, 7.0 and 7.1 ;)

**Comment by mbaeuerle** [comment]
Okay alright then I close this for now.
