### ISSUE TITLE
Allow user to list built-in/custom tasks

### ISSUE THREAD

**Issue by duraki** [andres-montanez/Magallanes#347]
This could be a really great option for debugging the deployment procedure, and it's usage would be fairly simple. We would need a command for example `mage:tasks:builtin` to list all built-in tasks possibly with description and usage, and `mage:tasks:custom` to list all custom tasks.

We could further extend the task listing by allowing dummy tests to be made directly instead of writing unit tests specifically.

A lot of times while writing custom tasks, I have to test deployment on my local environment (when not using dry-run), while instead, I could run a task and magically get the output if the task passed or failed because of syntax error or similar.

**Comment by andres-montanez** [comment]
Sounds cool!

**Comment by andres-montanez** [comment]
We'll rely on the documnetation page for the list of built in tasks.
For custom task we'll rely on the developer keen eyes.
