### ISSUE TITLE
Allow parallel deployment to hosts

### ISSUE THREAD

**Issue by dn5** [andres-montanez/Magallanes#349]
A parallel deployment means that the host(s) receive the same input and represent the output on hosts in the view of task execution. I've implemented some solution but it's quite hacked. The input is sent through `Thread` class in [Ruby](https://ruby-doc.org/core-2.2.0/Thread.html) which spawn several different shells of `php` (mage bin) with different config (environment) files. The solution works with Mage v1 but I'd rather not use it in production. On multiple hosts, there is probably a balancer so it doesn't matter if the shells are different id-based.
  
The way I'd go with is to parse pre-defined hosts so you can start several instances based on this.  

```magephp:
        ...
            fast: true
            hosts:
                - webserver1
                - webserver2
                - webserver3
            post-deploy:
               - ...
```  
 
Pseudo code would follow the same style but depending on the param `fast` which would then take all the hosts and run actions on them one by one. If the action in the first `thread` (host) is finished, the deploy continues with second action on that hosts, while others servers wait for their signal.
  
```php

public function deployFast($method = 'parallel')
{
    if (!$this->getFast()) {
       // continue normal
    }

    return $this->deploy($hosts);
}
```
  
I already plan to send pull request till the weekend but would love to hear your input.

**Comment by andres-montanez** [comment]
Hi @dn5 I appreciate your feedback, but currently PHP doesn't have a native threading, and by native I mean that you don't have to compile anything extra.
So parallel deployment is out of scope for the current version of Magallanes.
Regards.

**Comment by dn5** [comment]
We could achieve similar effect using `PCNTL` functions right now, by forking current input. The feature should stay experimental but I'm pretty sure this could be done easily internally. Of course, it's pseudo native, so as said, not for production usage.

**Comment by dn5** [comment]
Oh, lets not forget that parallel deployment was in the roadmap at the (I think) 1st presentation of Mage v1, right? :)

Anyway, I've looked upon other PHP based deployers and most of them works as I've explained in the issue topic. Here is the snip of the code from `deployer` tool:

```php
...
        foreach ($this->servers as $serverName => $server) {
            $process = new Process(
                "php " . DEPLOYER_BIN .
                (null === $deployPhpFile ? "" : " --file=$deployPhpFile") .
                " worker " .
                " --master 127.0.0.1:{$this->port}" .
                " --server $serverName" .
                " $input " .
                " $verbosity" .
                " &"
            );
            $process->disableOutput();
            $process->start();
        }
```

I have went with different way, compiled the PHP (7.0.15) with ZTE flags enabled that allows extending to `Thread` classes which extends from `Threaded`. Current phase check for ZTE and see if it's available. If it is, it then continues the deployment based on flag `fast=true|false`, sending the `hosts` to either `runOnHostActionParallel` or `runOnHostActionSingle`. Following that, it creates new `Parallel` object that extends from `Thread` and then have a simple callback through `call_user_func_array` with appropriate `runOnHost` method.

Will send a PR shortly.

**Comment by andres-montanez** [comment]
Hi! Thanks for the research, looks interesting.
Still having a feature based on a compile flag is not ideal.
Also the current scope of the project does not allow to invest effort in experimental features.

Cheers!

**Comment by dn5** [comment]
Ugh .. Okay, I guess? Another way would be to use [pssh](https://linux.die.net/man/1/pssh). It's native, it allows everything passed through base `ssh`, so rsync would work too. No matter how much I love this tool and it's way of working, it could never be used on a larger-scale codebase system since it lacks some basic deployment features.
