### ISSUE TITLE
Deployment worklfow clarification

### ISSUE THREAD

**Issue by zf2timo** [andres-montanez/Magallanes#359]
I'm new to Magallanes v3 and wanted to created a deployment for my project. Therefor I had a look at the default deployment and it's task. 
```YAML
            pre-deploy:
                - git/update
```
This executes the `UpdateTask` and when I see it correct, it executes a `git pull` in the current project to fetch all changes from the repository.

Because of this behavior, I assume, a deploy with `git/update` should be executed on the remote host. 

But when I don't like to have git installed on my live server I have to execute the deployment locally and copy all files to the remote host.
This leads to the question, what happens when I am currently developing a feature hand have to execute a deployment. When there are unstashed/uncommited changes in my repository, they will be also deployed to the remote host. And this can be really dangerous.

In my option, Magallanes should provide a workflow, to clone the repository in an empty folder and deploy those files to the remote host.
This is currently not possible, because everything is executed in the current folder.

What do you think to this proposal?

**Comment by andres-montanez** [comment]
Hi! Glad you are interested in Magallanes!

Ideally you will have a dedicated directory from which you will run the deployments, so you won't have modified files in there, and in this scenario the `git/update` task must be ran on the `pre-deploy` stage, so your specialized directory is updated.

From there your code will be copied. Currently clone the repository to a safe directory and proceed from there is out of scope, but I have a task for it #315 so it is in the roadmap.

**Comment by zf2timo** [comment]
Thank you for the fast response @andres-montanez 

Maybe it should be added and highlighted in the documentation to execute the deployment in a clean environment or did i misread something?

If I can help with #315 feel free to ask.
