### ISSUE TITLE
equivalent to "from:"

### ISSUE THREAD

**Issue by Havrin** [andres-montanez/Magallanes#361]
I started a new project with the new v3 of magallanes. Maybe I am missing something, I tried to copy and change my config of my old v1 projects to v3, but I am missing the `from:` parameter. I have my grunt, composer etc. stuff on root-level and a folder "http" with my project files I want to deploy. On v1 I used `from: ./http` in the configuration, now all vendor, node_modules files etc. are deployed too.

**Comment by andres-montanez** [comment]
Hi! That option was removed from V3.
Your .mage file should exists in the directory from where your deployment dir starts.
By your comment above, you should have your .mage.yml inside the http directory.

Regards.
