### ISSUE TITLE
Tar-Creation on mac adds ._*-Files

### ISSUE THREAD

**Issue by wlwwt** [andres-montanez/Magallanes#367]
Hi there,

I am having problems with using magallanes on macosx. 
Within the task "Running [Deploy] Preparing Tar file ..." a tar file is created in the systems temp dir. 

On mac this task adds a lot of ._* files to the archive which then spams the server.

Here are more infos on these files:
http://apple.stackexchange.com/questions/14980/why-are-dot-underscore-files-created-and-how-can-i-avoid-them

**Comment by andres-montanez** [comment]
Hi @wlwwt can you try add "._*" to the excludes files?
According to your link, this is a behaviour only to OSX.

Regards.

**Comment by wlwwt** [comment]
This solves the issue. Thanks for the hint.
