### ISSUE TITLE
Dynamic deploy path

### ISSUE THREAD

**Issue by etki** [andres-montanez/Magallanes#368]
Hi.
We develop stuff using git-flow in our team, and in some cases (such as deploying feature branches) do not know deploy path in advance (it should be `/var/www/<project-name>/<service-name>/feature/<feature-name>` in our convention, and we can't add support for every feature by hand). I think that it would be great to add such feature to Magallanes, possibly by overriding configuration options just using environment variables.

**Comment by andres-montanez** [comment]
Hi, thanks for your feedback. Currently this can't be done and I can't see an easy way to implement it.
I've been thinking about environment's aliasing and perhaps that could work for you.
Still right now this is not on the roadmap.

Thanks!

**Comment by etki** [comment]
@andres-montanez got it, thank you
