### ISSUE TITLE
Deploy to multiple environments at once

### ISSUE THREAD

**Issue by Toflar** [andres-montanez/Magallanes#369]
I use Mage to deploy the same setup to multiple hosts so what do you think about the `deploy` command just accepting an array of environments?

Right now it's `./vendor/bin/mage deploy prod1 && ./vendor/bin/mage deploy prod2` but imho it would be nice if I could just go for `./vendor/bin/mage deploy prod1 prod2`.

**Comment by andres-montanez** [comment]
Hi, that would require to change how the parameters are read, and will limit how the parameter can be used.

And because you can do it already (calling deploy twice) I'm going to pass on the feature for now.

Still, thanks for your feedback!
