### ISSUE TITLE
Define whitelist of files instead of exclude

### ISSUE THREAD

**Issue by aistis-** [andres-montanez/Magallanes#373]
Hi, is it possible to define the whitelist of files for deployment instead blacklist?

Some of the projects has a bunch of files, which should not be deployed and their number changes very often in the repository. However, we have only few files which need to be deployed, but those files are spread in various folders

How do you handle this scenario?

**Comment by andres-montanez** [comment]
Hi, currently this is not possible. I advice to review the project's structure.
For example all symfony projects have the temporal files in the /var/ directory, so it's easy to exclude just that directory.

Regards.
