### ISSUE TITLE
PHP bin location config

### ISSUE THREAD

**Issue by robertosanval** [andres-montanez/Magallanes#376]
I've different PHP versions in my local machine and deployment machine too.

How could I choose which `bin/php` command to use with Magallanes?

Thanks

**Comment by andres-montanez** [comment]
Hi, did you try something like this?
`/path/to/php7 bin/mage`
`/path/to/php5.6 bin/mage`
etc…
That could work.

Let me know!
Regards!

**Comment by robertosanval** [comment]
Yes, I've tried that, it's OK but the problem is with the php commands executed in Builtin Tasks like symfony/cache-warmup I'd like to chose the PHP version to execute those commands.

**Comment by andres-montanez** [comment]
Well, those are executed "as it is", so currently there is no workaround for that.
Do you have a proposal?

Regards!

**Comment by robertosanval** [comment]
How about to add a config parameter to magephp and each environment branch called php_bin?

**Comment by andres-montanez** [comment]
That could be a valid workaround. I will take it into account for the next release.
Thanks!

**Comment by robertosanval** [comment]
Thanks to you and your support!

**Comment by robertosanval** [comment]
As a temporary solution I've tried to modify bin/mage file first line from:

#!/usr/bin/env php

**Comment by andres-montanez** [comment]
Closing this for the moment.
