### ISSUE TITLE
Mage\Tests\Runtime\RuntimeMockup must be in autoload, not only in autoload-dev

### ISSUE THREAD

**Issue by b3nl** [andres-montanez/Magallanes#379]
We need the class Mage\Tests\Runtime\RuntimeMockup to test our custom tasks, but because it is only included in the composer/autoload-dev it is not auto-included in our projects. (http://stackoverflow.com/questions/26941046/composer-require-dev-autoload-from-package-not-added-to-projects-autoload) This file needs to be moved in the "production autoloader".

**Comment by andres-montanez** [comment]
This can be addressed at a test stage, so we'll keep things at def for now.
