### ISSUE TITLE
Abort if log folder is missing, create it or document the behaviour

### ISSUE THREAD

**Issue by b3nl** [andres-montanez/Magallanes#380]
If the configured log folder does not exist, nothing happens. "We wait" for the log, but it will not be created. I would suggest the tool tries to create it and aborts, if this is not possible.

**Comment by andres-montanez** [comment]
Hi, logging is optional, but I agree that a warning should be displayed.

**Comment by andres-montanez** [comment]
Hi, this will be covered in the next release.
