### ISSUE TITLE
Dry run option

### ISSUE THREAD

**Issue by seydu** [andres-montanez/Magallanes#39]
Hi. 
This seems to be the exact library I was looking for ! Thank you for that.
I used to run commands like those in Magallanes in a very awkward code, written in Shell scripts. I couldn't even get my co-workers to help me maintain the code.
The install of Magallanses using Composer is smooth, so is the configuration. 
But I have two questions:
1/ Is there a way to do a dry-run ? If yes how ?
2/ For the connection without a passphrase, how can I set the path to the private key file ? The only way I found is by defining an alias in ~/.ssh/config and using the Host alias in the environment configuration.

**Comment by andres-montanez** [comment]
Hi, Version 1 of Magallanes has long reached it's end of life cycle, so no further changes will be integrated to it, focus is for the next next mayor version.
Many thanks!
