### ISSUE TITLE
Add a log_max_files config

### ISSUE THREAD

**Issue by Toflar** [andres-montanez/Magallanes#403]
My `log_dir` stacks up log files and I only need the last few of them, I think it would be great if mage deleted the old ones for me. Locally, I can delete them manually but as soon as you start working with Jenkins and stuff, the workspace grows rather big :-)

**Comment by andres-montanez** [comment]
Hi @Toflar! A new `log_limit` option (defaults to 30) will be available on V5!
Thanks!
