### ISSUE TITLE
Malformed ssh command when specifying port directly on hosts

### ISSUE THREAD

**Issue by humbkr** [andres-montanez/Magallanes#405]
Hello,

The prepare-release task is not working when specifiying a port directly in the hosts configuration, because the generated command is malformed:

When specifiying the port using "hosts: - <hostname>:<port>"
ssh -p 2222 -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no www-data@163.172.24.193:2222 "mkdir -p /path/to/releases/20171206125517"

=> double port definition in ssh command, does not work

When specifiying the port using "ssh: port:"
ssh -p 2222 -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no www-data@163.172.24.193 "mkdir -p /path/to/releases/20171206125517"

=> port is only defined with -p option, works

**Comment by andres-montanez** [comment]
Hi, this will be fixed in the next release.
Thanks!
