### ISSUE TITLE
Not compatible with Symfony 4

### ISSUE THREAD

**Issue by thbergler** [andres-montanez/Magallanes#406]
Hello,
the actual version is not compatible with Symfony 4.

When will be a version for Symfony 4 avaible?

Best regards
Thorsten

**Comment by netsuo** [comment]
Any update on this @andres-montanez  ? This is really blocking for me, because I use magephp in all my projects and some are starting to be on SF4.

It would be catastrophic to have to change my deployment process for all of them

Thanks

**Comment by aschempp** [comment]
I guess this can be closed? 😄

**Comment by andres-montanez** [comment]
LOL, yes :D
