### ISSUE TITLE
Parallel deployment

### ISSUE THREAD

**Issue by hco** [andres-montanez/Magallanes#41]
I'm currently using capistrano, but I'm not completly happy with it.
I really like the simplicity of Magallanes, and it's close to what I would have written myself, but I'm missing parallel execution of the steps.
For instance, uploading & extracting of the .tgzs would be faster if it would happen on all hosts at the same time.

**Comment by ZesInternational** [comment]
+1

**Comment by psren** [comment]
This one would be super nice.

**Comment by purch-FE** [comment]
Hey there, 
@DaFox did you pushed a pull request ?
@andres-montanez  Is it possible to merge the @DaFox version if it's ok and working well ?

**Comment by andres-montanez** [comment]
Hi, Version 1 of Magallanes has long reached it's end of life cycle, so no further changes will be integrated to it, focus is for the next next mayor version.
Many thanks!
