### ISSUE TITLE
[feature request] Dynamic test environments

### ISSUE THREAD

**Issue by UncleTawnos** [andres-montanez/Magallanes#410]
I'd like to be able to change path on host depending on some ENV variable I can set at CI tool
The scenario is: there are multiple branches to be deployed to test server to apache virtual directories
there is a vhost responding to <jira-task-number>.test.domain.com and code after being built by CI should be deployed into /srv/www/tests/<jira-task-number>/current

Currently, as far as I know there is no option to change deployment path on a variable. At the moment I'm using sed on .mage.yml to "tweak" it on each build, but something built-in would be welcome

ideally would be if we could overwrite any config element just like --branch

**Comment by andres-montanez** [comment]
This should be addressed by having different entries in your `.mage.yml` config file, defining one entry per environment.
