### ISSUE TITLE
project abandoned?

### ISSUE THREAD

**Issue by fritzmg** [andres-montanez/Magallanes#431]
I am just wondering whether this project is abandoned. The last commit was in April 2018 and so far there was no response to any of the pull requests. Also the website https://www.magephp.com/ has recently gone offline (though it already did so once one year ago).

**Comment by andres-montanez** [comment]
Hi, the project is on hiatus, sorry about the web (it's up now again).
Eventually I will resume some of the works here, but the tool is very capable with the current features enabled, so there isn't a real need for improvement.
Thanks for your concern!

**Comment by fritzmg** [comment]
Ok, thanks for the heads up :)
