### ISSUE TITLE
Install fails in Laravel project

### ISSUE THREAD

**Issue by jfoucher** [andres-montanez/Magallanes#432]
When installing Magellanes 3.0 in a Laravel 5.5 project I get the following errors : 

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install andres-montanez/magallanes 3.4.0
    - Conclusion: don't install andres-montanez/magallanes 3.3.0
    - Conclusion: don't install andres-montanez/magallanes 3.2.0
    - Conclusion: don't install andres-montanez/magallanes 3.1.0
    - Conclusion: don't install andres-montanez/magallanes 3.0.1
    - Conclusion: remove symfony/event-dispatcher v4.2.2
    - Installation request for andres-montanez/magallanes ^3.0 -> satisfiable by andres-montanez/magallanes[3.0.0, 3.0.1, 3.1.0, 3.2.0, 3.3.0, 3.4.0].
    - Conclusion: don't install symfony/event-dispatcher v4.2.2
```

And so on but you get the gist of it

If I install Magellanes 4.* I get similar errors : 
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for andres-montanez/magallanes ^4.0 -> satisfiable by andres-montanez/magallanes[4.0.0].
    - Conclusion: remove symfony/console v3.4.21
    - Conclusion: don't install symfony/console v3.4.21
    - andres-montanez/magallanes 4.0.0 requires symfony/console ^4.0 -> satisfiable by symfony/console[v4.0.0, v4.0.1, v4.0.10, v4.0.11, v4.0.12, v4.0.13, v4.0.14, v4.0.15, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.1, v4.1.10, v4.1.11, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.0, v4.2.1, v4.2.2, v4.2.3].
```

It seems Laravel uses some symfony 4 components and some Symfony3 components and Magellanes needs one or the other. Is there a way this can be fixed ?
Thanks

**Comment by andres-montanez** [comment]
Hi, according to your log, the conflict is in `symfony/event-dispatcher v4.2.2`.
Magallanes 3 requires symfony 3. If you have a dependency on symfony 4 components, you can install Magallanes 4.
Cheers!

**Comment by jfoucher** [comment]
Thanks for the quick reply. The issue stemmed from the fact that some dependencies used symfony 4 components and some others used symfony 3 components. I forced everything to use Symfony 3 components and installed Magellanes 3 and everything worked.
BTW major kudos for using the same version number as the symfony version you're currently depending on, that simplifies things a lot !
