### ISSUE TITLE
outdated SSL certificate on magephp.com

### ISSUE THREAD

**Issue by m-vo** [andres-montanez/Magallanes#433]
Just wanted to inform you that the SSL certifificate on https://www.magephp.com/ is outdated since 1st of march (`SEC_ERROR_EXPIRED_CERTIFICATE`).

**Comment by andres-montanez** [comment]
Thanks mate! Already solved! ;)

**Comment by q2dg** [comment]
Well, in fact, this project seems pretty abandoned...
