### ISSUE TITLE
Cannot install in Symfony 5 project because of console dependency

### ISSUE THREAD

**Issue by jahrralf** [andres-montanez/Magallanes#443]
Hi, I am trying to include Magallanes in a symfony 5 project. This comes with symfony/console 5.0 which is higher than the 4.0 required by Magallanes. How can I solve this? Is there any way to build/get a phar? Would help here. Thanks!

```
        "symfony/console": "5.0.*",
```

```
$ php composer.phar require andres-montanez/magallanes
Using version ^4.0 for andres-montanez/magallanes
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "5.0.*"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for andres-montanez/magallanes ^4.0 -> satisfiable by andres-montanez/magallanes[4.0.0].
    - andres-montanez/magallanes 4.0.0 requires symfony/console ^4.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
```

**Comment by vgross** [comment]
Same issue here, did you find a solution by any chance?

**Comment by jahrralf** [comment]
No - lost my interest, no good solution so far.

**Comment by hauke68** [comment]
I fixed that and created a PR.
The fix works here in our environment, but better should be tested by other developers.

**Comment by hauke68** [comment]
Well, give me some time to prepare and deploy a release. I am currently busy at work.
Good you deployed the alpha release ;-)

**Comment by ElGittoJunior** [comment]
I was able to deploy with Symfony 5.1.5 with it. As far working like a charm. Thank you!
I did the alpha release because I was in hurry, and I need to run composer. But it's your work and I would switch to your version.

**Comment by hauke68** [comment]
@ElGittoJunior  Released on Packagist ;-)

**Comment by ElGittoJunior** [comment]
@hauke68 Thank you! I switched to your version. Works fine so far!

**Comment by 2618094** [comment]
in 4.1.0 symfony5 is supported
