### ISSUE TITLE
v4.1.0: New behavior / bug in build in Tar/PrepareTask.php

### ISSUE THREAD

**Issue by timotrautmann** [andres-montanez/Magallanes#449]
The following change breaks our deployment process:
https://github.com/andres-montanez/Magallanes/commit/eae991dc6022b50cacd4841a94672304a5ae80d6#diff-8ff203ed23bf6cb6c197b5d7c64f0dc2b5b8c37187af339118e37fe8af72b24d

We only deploy a subfolder ./htdocs of our repository to the webserver. So we use the option "from: ./htdocs".
The old behavior was that, this code was transported to releases/20210219113743/htdocs.
The new behavior is, that now the code is transported directly to releases/20210219113743

We have other tasks, which creates further directories in releases/20210219113743
There is no possibility to get the old behavior back.

We have no change to use the new version. In our opinion this is a bug.

**Comment by andres-montanez** [comment]
Hi @timotrautmann , I will take a deeper look today.
Thanks for your quick comment!!

**Comment by andres-montanez** [comment]
Hi! I've pushed the fix in version 4.1.1.
Regards!

**Comment by timotrautmann** [comment]
Thanks!
