### ISSUE TITLE
Clickjacking security issue: Missing X-Frame-Options header

### ISSUE THREAD

**Issue by pikpikcu** [andres-montanez/Magallanes#452]
Issue Vulnerability Clickjacking: **https://www.magephp.com**
#### Vulnerability Description

Clickjacking (User Interface redress attack, UI redress attack, UI redressing) is a malicious technique of tricking a Web user into clicking on something different from what the user perceives they are clicking on, thus potentially revealing confidential information or taking control of their computer while clicking on seemingly innocuous web pages.

The server didn't return an X-Frame-Options header which means that this website could be at risk of a clickjacking attack. The X-Frame-Options HTTP response header can be used to indicate whether or not a browser should be allowed to render a page in a or <iframe>. Sites can use this to avoid clickjacking attacks, by ensuring that their content is not embedded into other sites.
This vulnerability affects Web Server.
Steps to reproduce the vulnerability

Create a simple html file with the following content and open it in a browser:
```html
<html>
 <head>
  <title>Clickjack test page</title>
 </head>
 <body>
  <p>clickjacking! Vulnerable</p>
  <iframe src="https://www.magephp.com" width="1000" height="1000"></iframe>
 </body>
</html>

```

**Comment by andres-montanez** [comment]
Thanks! I've added the header.

Much appreciated!
