### ISSUE TITLE
Password override

### ISSUE THREAD

**Issue by JoeSimsen** [andres-montanez/Magallanes#48]
Hello Andres,

First of all, great tool! I am currently trying to implement the tool in my projects. For ease of use we would like to add the password in the config, so it is included in the ssh/scp request. The program is going to be used on many different machines, so it would be preferable for it to be as much copy paste as possible.

It is definitely possible, and easy to implement. Any reason i isn't, and could it be an optional implementation in the future?

**Comment by andres-montanez** [comment]
Hi, Version 1 of Magallanes has long reached it's end of life cycle, so no further changes will be integrated to it, focus is for the next next mayor version.
Many thanks!
