### ISSUE TITLE
Current release doesn't include git deployment

### ISSUE THREAD

**Issue by Danielss89** [andres-montanez/Magallanes#80]
Hi

On the website you suggest git-rebase as a strategy, the code for it exists but the DeployCommand doesn't know of it:
https://github.com/andres-montanez/Magallanes/blob/a97d172a6d1b87aeab6d5a50f939b5ac00e6a906/Mage/Command/BuiltIn/DeployCommand.php#L301-L322

**Comment by schaetzle** [comment]
Yeah. I also wasted a lot of time. Please add this information in your documentation as long as deployment via git doesn't work.
