### ISSUE TITLE
Fail when doing the Releasing

### ISSUE THREAD

**Issue by Geus** [andres-montanez/Magallanes#92]
Hi andres, how are you? 

I'm starting to use your awesome tool, but i'm facing a bit of problem. I created a pair of custom tasks to deploy a Symfony2 app and everything is working with those tasks, but now I'm getting a FAIL when the deploy task is finishing.

This is what I get:

```
        Starting the Releasing
                Releasing on host example.com:2222 ... FAIL
        Finished the Releasing
```

As this fails, the 'current' link isn't updated.

When I see at the logs, I don't see anything weird, so I dug a bit, and found that the exec of the command is returning a 255 error code. 

The thing is that if I execute those commands (which I see on the logs) on my shell, they are executed without errors. 

Additional info:
- I'm using the Symfony3 folder structure (so I had to change some of the BuiltIn Tasks to point to the right 'bin/console')
- On one of my custom tasks, I create a dynamic link to the uploads dir.

Thanks in advance,
Guillermo

**Comment by ChrisWesterfield** [comment]
This issue still exists and is not solved.
I'm currently getting the same issue as mentioned above.

The command executes with return code 255 as well.
Did anyone ever find an solution?
