### ISSUE TITLE
Cumbersome to test own custom tasks

### ISSUE THREAD

**Issue by voukka** [andres-montanez/Magallanes#94]
There are no tests for Mage... :(
I try writing tests for my own Tasks, but it is almost impossible(please see a workaround below) to create an instance a custom Task without having to create new testing.yml file.  Ugh.

So in the problem is that
-  - constructor requires parameter of type Config , so you cannot pass there mock of Config
-  - ok, then you want to mock your Task instance without calling constructor, fine but
-  ::getParameter() relies on the property set in the constructor.
- So the workaround is to add a child abstract class that
-  - adds getter ::getParameters()
-  - redefines implementation of ::getParameter() to use that new getter.

This workaround enables you to mock all getters for properties set in the constructor

Overall, it'd be very nice to consistently use getters for properties, which would make the code mocking--friendly.

**Comment by eps90** [comment]
I've just found another issue. Some of methods, for example `AbstractTask::runCommand` are marked as final. Yesterday I was coding some unit tests for built-in tasks and I didn't know why I couldn't stub that method (simply to not to run given command, I just wanted to place some expectation of calling it). Finally I found the reason.
So do we really need final methods? I know there are security reasons to not overwrite method's body. I could also create my own class mock but it makes the tests dirty.
What do you think?

**Comment by andres-montanez** [comment]
Hi all, Version 1 of Magallanes has long reached it's end of life cycle, the next mayor version will be far more Test Friendly.
Many thanks to all!
